# TELEGRAF CONFIGURATION

# --- SEÇÃO DE ENTRADA (Lendo do MQTT) ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "teg/telemetry"
  ]
  data_format = "json"
  # O Telegraf vai criar uma tabela chamada 'teg_telemetry' no banco
  name_override = "teg_telemetry" 

# --- SEÇÃO DE SAÍDA (Escrevendo no TimescaleDB) ---
[[outputs.postgresql]]
  connection = "postgres://postgres:senha_super_secreta@timescaledb:5432/teg_db?sslmode=disable"